version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  consumer:
    build: .
    container_name: mq_consumer
    command: python consumer.py
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  publisher:
    build: .
    container_name: mq_publisher
    command: python publisher.py
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONUNBUFFERED=1i
    depends_on:
      rabbitmq:
        condition: service_healthy
      consumer:
        condition: service_started